id: PB0CAB882
initial_creation_type: ocr
source_metadata:
  volumes:
    5e5328c830b44aeda7eb8cc4a4a4720c:
      base_file: v056.txt
      image_group_id: I1PD95901
      title: ཤེས་རབ་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་སྙིང་པོ་ཞེས་བྱ་བའི་འགྲེལ་པ།
      total_pages: 1682
      volume_number: 56
